Facility admin add vitals to appointment page sept2
dccabs/housecallmd pull request #431
Opened 2022-09-02 09:03 UTC by lourdesyang1023

2022-09-02 15:05 UTC, dccabs requested changes
Please check the comments

2022-09-02 15:05 UTC, dccabs commented on pages/facility/admin/appointment/[id].js
> +                  {data?.vitals_temperature ?? 'No value entered'}
Please add some space between the Temperature: ${value}. right now there is no space.

2022-09-02 15:05 UTC, dccabs commented on pages/facility/admin/appointment/[id].js
> +                <Box style={{ textDecoration: 'underline' }}>
please remove the underline.

2022-09-03 01:00 UTC, lourdesyang1023 commented
> Please check the comments

Made changes and pushed

2022-09-03 18:53 UTC, dccabs approved these changes

2022-09-03 18:53 UTC, merged