Contact redesign oct4
dccabs/housecallmd pull request #515
Opened 2022-10-04 06:28 UTC by brentbagapuro

2022-10-04 18:59 UTC, dccabs commented
Please replace the dummy information with what we have on the housecall contact us form now

![Screen Shot 2022-10-04 at 1 57 46 PM](https://user-images.githubusercontent.com/558687/193903204-9c02b5ed-c7e3-4cd2-8383-c9dcf22739a4.png)

Please replace the MUI snackbar with a notification modal.

Please put in a modal if there is an error with the submission.

Right now I'm still seeing default MUI fonts.  Basically we want to strip MUI out of this application on the customer side.  So ideally we can figure out a way to strip out all MUI.  We do want to keep it on the admin side for now.

Thanks 

-dan

2022-10-04 19:00 UTC, dccabs requested changes
Hi Brent, please see comments for changes. Thank you.

2022-10-04 19:00 UTC, dccabs commented on pages/contact.js
> +const CotnactPage = () => {
Please correct spelling here.

2022-10-05 18:16 UTC, dccabs commented on pages/contact.js
> +    setOpenDialog(true)
This should be put in the success portion of the fetch request.  Right now it calls before the submission is made.

2022-10-05 18:16 UTC, dccabs commented on pages/contact.js
> +    setOpenDialog(true)
Can we add a loading indicator that the message is sending.

2022-10-07 06:01 UTC, brentbagapuro commented
Fixed all merge issues. This branch is ready to merge to housecall_tailwinds_ui

2022-10-07 12:46 UTC, merged