reviews redesign
dccabs/housecallmd pull request #528
Opened 2022-10-10 08:31 UTC by brentbagapuro

- Integrated Review List content from contenful into homepage
- Reviews component to tailwind
- ReviewItem component

2022-10-10 21:13 UTC, dccabs requested changes

2022-10-10 21:13 UTC, dccabs commented on pages/index.js
>            <div className={classes.reviewsContainer}>
Please get rid of all MUI stuff.  

That incudes any useStyles, Box, etc.  This should be strictly tailwinds ui. Thanks

2022-10-10 21:16 UTC, dccabs commented on pages/index.js
>            <div className={classes.reviewsContainer}>
Please change the gray background to white, remove the double "Reviews" headers so that it just has one.  Tight up the spacing.  should look similar to this.

<img width="1258" alt="Screen Shot 2022-10-10 at 3 15 28 PM" src="https://user-images.githubusercontent.com/558687/194953585-7db294ab-ded2-4071-8e5a-702ddbf4d142.png">

2022-10-10 21:17 UTC, dccabs commented on pages/index.js
>            <div className={classes.reviewsContainer}>
Please also change the date under the name to MM/DD/YYYY

2022-10-11 06:23 UTC, brentbagapuro commented on pages/index.js
>            <div className={classes.reviewsContainer}>
Just pushed changes for these

2022-10-11 10:00 UTC, dccabs approved these changes
looks good thanks.

2022-10-11 10:00 UTC, merged